### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SoumenDass** [jashandeep-sohi/webcam-filters#2]
1. Created a virtualenv
2. Installed pipx
3. Got below error:

```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Could not find a version that satisfies the requirement webcam-filters (from versions: none)
ERROR: No matching distribution found for webcam-filters
```
$ python3 --version
Python 3.7.7

**Comment by jashandeep-sohi** [comment]
- Can you install other packages? i.e.  does `pipx install cowsay` work?
- Did you run `pipx ensurepath`?
- Can even use pipx from within a virutalenv :thinking:

**Comment by SoumenDass** [comment]
Yes I can install pipx cowsay from within the virtualenv. I ran pipx ensurepath. Since I could install cowsay within the virtualenv and run cowsay sucessfully, I think it works fine.

**Comment by jashandeep-sohi** [comment]
Ah...missed this. pip should really have a better message when it fails these types of checks.
```
$ python3 --version
Python 3.7.7
```
But https://github.com/jashandeep-sohi/webcam-filters/blob/5e7860b92d69a340aa49c47c84a597f4ef8a4f4e/pyproject.toml#L12

Now why is it that? Because that's what I was working with.

Will it work with 3.7? I don't know.
Is there a way to force install?  pip has  `--ignore-requires-python`

**Comment by SoumenDass** [comment]
I tried with that option but got another error:

```
 ERROR: Could not find a version that satisfies the requirement mediapipe<0.9.0,>=0.8.6 (from webcam-filters) (from versions: none)
ERROR: No matching distribution found for mediapipe<0.9.0,>=0.8.6 (from webcam-filters)
```

**Comment by jashandeep-sohi** [comment]
Yeah, that looks like now mediapipe is complaining about the python version. Perhaps, `--ignore-requires-python` does not apply to dependencies. Maybe you can set https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-python-version to 3.9?

**Comment by jashandeep-sohi** [comment]
Closing. Not going to support python 3.7. As an alternative you can try installing with Nix:

`nix-env --file https://github.com/jashandeep-sohi/webcam-filters/archive/refs/tags/v0.2.2.tar.gz --install`
