### ISSUE TITLE
Zoom now natively supports Virtual Background images without a green screen on Linux

### ISSUE THREAD

**Issue by captn3m0** [jashandeep-sohi/webcam-filters#6]
Just a PSA issue. This is supported since the August 20, 2021 release `version 5.7.6 (31792.0820)`.

Changelog says:

>Support for Virtual Background images without a green screen - Linux
>The ability to use the Image as Virtual Background feature without the need of a green screen is now supported on Linux. System requirements will be provided in the Virtual [Background System Requirements Support article](https://support.zoom.us/hc/en-us/articles/360043484511).

The requirements seem modest:

```
    Zoom desktop client, version 5.7.6 or higher
    Supported processors 
        Intel i3 
            4 cores or higher
            8th generation or higher
        Intel i5
            4 cores or higher
            6th generation or higher
        Intel i7
            4 cores or higher
            4th generation or higher
        Intel i9 
            4 cores or higher
            4th generation or higher
        Intel Xeon
            4-cores or higher
            2.0Ghz or higher
        AMD
            8 logical cores or higher
            3.0Ghz or higher
```

It does include a "Blur" filter along with the regular virtual background stuff.

**Comment by igorhvr** [comment]
> Just a PSA issue. This is supported since the August 20, 2021 release `version 5.7.6 (31792.0820)`.
> 
> Changelog says:
> 
> > Support for Virtual Background images without a green screen - Linux
> > The ability to use the Image as Virtual Background feature without the need of a green screen is now supported on Linux. System requirements will be provided in the Virtual [Background System Requirements Support article](https://support.zoom.us/hc/en-us/articles/360043484511).
> 
> The requirements seem modest:
> 
> ```
>     Zoom desktop client, version 5.7.6 or higher
>     Supported processors 
>         Intel i3 
>             4 cores or higher
>             8th generation or higher
>         Intel i5
>             4 cores or higher
>             6th generation or higher
>         Intel i7
>             4 cores or higher
>             4th generation or higher
>         Intel i9 
>             4 cores or higher
>             4th generation or higher
>         Intel Xeon
>             4-cores or higher
>             2.0Ghz or higher
>         AMD
>             8 logical cores or higher
>             3.0Ghz or higher
> ```
> 
> It does include a "Blur" filter along with the regular virtual background stuff.

Browser-based Zoom does not support blur yet, so this is still useful for folks to prefer to use it web-based-only (instead of installing their client)...

**Comment by jashandeep-sohi** [comment]
Thanks for the heads up. Added a note to the readme.
